name: Makefile CI

on:
  push:
    branches: 
      - master
      - 4-use-github-actions-to-enable-automated-building-and-testing-of-the-project
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and Build
      run: install
      run: make

    - name: Run Tests
      run: make test
      