name: Makefile CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize vcpkg submodule
        run: git submodule update --init --recursive

      - name: Install dependencies and Build
        run: |
          make install
          make

      - name: Run Tests
        run: make test
        